apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: diagnose
  name: diagnose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diagnose
  serviceName: diagnose
  template:
    metadata:
      labels:
        app: diagnose
    spec:
      containers:
      - name: diagnose
        image: gcr.io/eoscanada-shared-services/diagnose:0c7797d
        command:
        - /app/diagnose
        args:
        - --eosdb-connection=eoscanada-public:bigtable-instance:5fff-v6
        - --blocks-store=gs://eoscanada-public-nodeos-archive/nodeos-mainnet-v8
        - --search-indexes-store=gs://eoscanada-public-indices-archive/search-aca3-v7
        - --namespace=default
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      restartPolicy: Always
