apiVersion: v1
kind: ServiceAccount
metadata:
  name: diagnose
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: diagnose
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: diagnose
subjects:
- kind: ServiceAccount
  name: diagnose
roleRef:
  kind: Role
  name: diagnose
  apiGroup: rbac.authorization.k8s.io
